/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:0bdcf6cb-7748-429c-9e79-e53626994b92",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_tbmqJuBik",
    "aws_user_pools_web_client_id": "6p9pab1bhaq3ca8h0e9njovifc",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://3isekvgmmbcjfh55nctgm6xr6a.appsync-api.ap-northeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4vlvcqef7javje4d4qkofa6exi"
};


export default awsmobile;
